### ISSUE TITLE
"Log" (Log||h^*(x^*,w^*||) in the eq.7 seems missing in the code. 

### ISSUE THREAD

**Issue by HantaoShu** [johnwlambert/dlupi-heteroscedastic-dropout#5]
Hi John Lambert,
I wonder the "log" in the eq.7 is missing in the code.  I checked the code in line 142/144 (dlupi-heteroscedastic-dropout/cnns/models/vgg_dlupi_model.py) and code in line 24(dlupi-heteroscedastic-dropout/cnns/train/modular_loss_fns.py ). I didn't find the "log" operation which is inconsistent with eq.7 in the paper.
Do I miss some important thing? Looking for your reply.

**Comment by johnwlambert** [comment]
Hi @HantaoShu, thanks for your interest in our work and for your attention to detail. Indeed you are right -- we are directly using a norm penality on $\sigma$'s, instead of a norm penalty on $\log \sigma$'s. 

This was intentional, however. As I remember we tried training with and without the log term in the loss, and the DLUPI models performed well/roughly equally under both losses, so I believe we left it out in the final code.

**Comment by johnwlambert** [comment]
Closing the issue for now, feel free to re-open if you have further questions.
